### PR TITLE
Add support for web platform

### PR DESCRIPTION
**Pull request by keyur2maru**

### CODE REVIEW

**Comment by chipweinberger** [comment]
thanks!

please do the other changes in a different PR!

**Comment by chipweinberger** [comment]
actually I'll be honest, I don't plan to maintain any other platforms besides the ones i need.

So i suggest you maintain this fork yourself. I will link to it in the readme.

**Comment by keyur2maru** [comment]
Sure no problem! Thanks for building this package, it is exactly what I was looking for!

**Comment by chipweinberger** [comment]
Added your fork to the README!

im open to improvements to IOS!

**Pull request closed without merging**
