### PR TITLE
background audio in ios fix

### PR DESCRIPTION
**Pull request by wsievern**
enable continuous audio playback in the background for iOS devices

### CODE REVIEW

**Comment by chipweinberger** [comment]
nice!

But this should be an option during setup.

In my app, I don't want background audio.

**Comment by wsievern** [comment]
ok, will adjust

**Comment by wsievern** [comment]
hey chip,

I tested compatibility on macOS, android, and iOS with dart_melty_soundfont playing back MIDI files. background audio in Android didn't require any changes for me

**Comment by chipweinberger** [comment]
looks good! thanks!!

**Pull request merged**
